name: Import Data to Auth0 from Google Drive

on:
  workflow_dispatch:
    inputs:
      target_tenant:
        description: 'Target Tenant'
        required: true
        type: choice
        options:
          - DEV
          - STAGE
          - PROD
        default: 'DEV'
      file_name:
        description: 'Source File'
        required: true
        type: string
        default: 'Application_Access_Management_v3.xlsx'
jobs:
  import_data:
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Auth0-Import.yml@main
    with:
      branch_name: 'main'
      target_folder: 'target'
      # Options 'google_drive', 'repository'
      source: 'google_drive'
      auth0_import_tenant: ${{ github.event.inputs.target_tenant }}
      auth0_resource_server: ${{ vars.auth0_resource_server }}
      input_file: ${{ github.event.inputs.file_name }}
    secrets:
      auth0_secrets: ${{ secrets.AUTH0_CREDENTIALS }}
      gcp_service_account: ${{ secrets.NABARUN_FIREBASE_SERVICE_ACCOUNT_STAGE }}
